apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  azurestorageaccountname: c3RyZ2xucA==

  azurestorageaccountkey: M1ZUVi9vV0lISjFTeHNtTGNicFhlVHBHc0VoVVljNlo5dHM0WFI3dGlDeEdKVWtoaXNlZTRRODFCREYzRjFTQ0N5M3JRbFhFb1p5aStBU3RaUFY1V3c9PQ==
